//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class wucMerchantTicketClone
{

	/// <summary>
	/// txtDBA control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txtDBA;

	/// <summary>
	/// MerchantID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox MerchantID;

	/// <summary>
	/// SettlePlatformMid control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox SettlePlatformMid;

	/// <summary>
	/// AgentDBA control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox AgentDBA;

	/// <summary>
	/// BusinessLegalName control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox BusinessLegalName;

	/// <summary>
	/// AchID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox AchID;

	/// <summary>
	/// MerchantAppTypeUID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.DropDownList MerchantAppTypeUID;

	/// <summary>
	/// AgentID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox AgentID;

	/// <summary>
	/// FMAID control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox FMAID;

	/// <summary>
	/// MLEName control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox MLEName;

	/// <summary>
	/// btnSearch control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnSearch;

	/// <summary>
	/// btnCloneTicket control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnCloneTicket;

	/// <summary>
	/// btnClose control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnClose;

	/// <summary>
	/// lblRecordCount control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label lblRecordCount;

	/// <summary>
	/// pnlRecords control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel pnlRecords;

	/// <summary>
	/// grd control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.GridView grd;

	/// <summary>
	/// odsTransactions control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.ObjectDataSource odsTransactions;

	/// <summary>
	/// pnlNoRecords control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel pnlNoRecords;

	/// <summary>
	/// Label1 control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label Label1;

	/// <summary>
	/// Panel1 control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel Panel1;

	/// <summary>
	/// grd2 control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.GridView grd2;

	/// <summary>
	/// dlgOK control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.UpdatePanel dlgOK;

	/// <summary>
	/// updateProgress control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.UpdateProgress updateProgress;

	/// <summary>
	/// pnlOK control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel pnlOK;

	/// <summary>
	/// txtIssue control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txtIssue;

	/// <summary>
	/// issueError control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label issueError;

	/// <summary>
	/// txtDueDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.TextBox txtDueDate;

	/// <summary>
	/// ddlDueDateTime control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.DropDownList ddlDueDateTime;

	/// <summary>
	/// CloneCalDueDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::AjaxControlToolkit.CalendarExtender CloneCalDueDate;

	/// <summary>
	/// CloneImgDueDate control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.ImageButton CloneImgDueDate;

	/// <summary>
	/// dueDateError control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label dueDateError;

	/// <summary>
	/// chbNotesClone control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.CheckBox chbNotesClone;

	/// <summary>
	/// chbAttachmentsClone control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.CheckBox chbAttachmentsClone;

	/// <summary>
	/// btnOK control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnOK;

	/// <summary>
	/// btnCancel control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnCancel;

	/// <summary>
	/// pnlResult control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel pnlResult;

	/// <summary>
	/// grdResult control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.GridView grdResult;

	/// <summary>
	/// btnDone control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button btnDone;

	/// <summary>
	/// mdError control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel mdError;

	/// <summary>
	/// mdPanel1 control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Panel mdPanel1;

	/// <summary>
	/// mdMsg control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Label mdMsg;

	/// <summary>
	/// mdClose control.
	/// </summary>
	/// <remarks>
	/// Auto-generated field.
	/// To modify move field declaration from designer file to code-behind file.
	/// </remarks>
	protected global::System.Web.UI.WebControls.Button mdClose;
}
