//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ZeusWeb.MDocWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FileUploadSoap", Namespace="http://MDocWS/")]
    public partial class FileUpload : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefreshLookupTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileWithSourceAndUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FileUpload() {
            this.Url = global::ZeusWeb.Properties.Settings.Default.ZeusWeb_MDocWS_FileUpload;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteFileCompletedEventHandler DeleteFileCompleted;
        
        /// <remarks/>
        public event GetFileCompletedEventHandler GetFileCompleted;
        
        /// <remarks/>
        public event RefreshLookupTableCompletedEventHandler RefreshLookupTableCompleted;
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event UploadFileWithSourceCompletedEventHandler UploadFileWithSourceCompleted;
        
        /// <remarks/>
        public event UploadFileWithSourceAndUserCompletedEventHandler UploadFileWithSourceAndUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/DeleteFile", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteFile(int DocID, int MerchantID, int AgentID, int PrimaryKeyID) {
            object[] results = this.Invoke("DeleteFile", new object[] {
                        DocID,
                        MerchantID,
                        AgentID,
                        PrimaryKeyID});
            return ((bool)(results[0]));
        }

        /// PXP-7623 Rohit Thakur
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/DeleteFileWithUser", RequestNamespace = "http://MDocWS/", ResponseNamespace = "http://MDocWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteFileWithUser(int DocID, int MerchantID, int AgentID, int PrimaryKeyID, string UserName)
        {
            object[] results = this.Invoke("DeleteFileWithUser", new object[] {
                        DocID,
                        MerchantID,
                        AgentID,
                        PrimaryKeyID,
                        UserName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int DocID, int MerchantID, int AgentID, int PrimaryKeyID) {
            this.DeleteFileAsync(DocID, MerchantID, AgentID, PrimaryKeyID, null);
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int DocID, int MerchantID, int AgentID, int PrimaryKeyID, object userState) {
            if ((this.DeleteFileOperationCompleted == null)) {
                this.DeleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileOperationCompleted);
            }
            this.InvokeAsync("DeleteFile", new object[] {
                        DocID,
                        MerchantID,
                        AgentID,
                        PrimaryKeyID}, this.DeleteFileOperationCompleted, userState);
        }
        
        private void OnDeleteFileOperationCompleted(object arg) {
            if ((this.DeleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileCompleted(this, new DeleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/GetFile", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MDoc GetFile(int DocID, int MerchantID, int AgentID, int PrimaryKeyID) {
            object[] results = this.Invoke("GetFile", new object[] {
                        DocID,
                        MerchantID,
                        AgentID,
                        PrimaryKeyID});
            return ((MDoc)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileAsync(int DocID, int MerchantID, int AgentID, int PrimaryKeyID) {
            this.GetFileAsync(DocID, MerchantID, AgentID, PrimaryKeyID, null);
        }
        
        /// <remarks/>
        public void GetFileAsync(int DocID, int MerchantID, int AgentID, int PrimaryKeyID, object userState) {
            if ((this.GetFileOperationCompleted == null)) {
                this.GetFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileOperationCompleted);
            }
            this.InvokeAsync("GetFile", new object[] {
                        DocID,
                        MerchantID,
                        AgentID,
                        PrimaryKeyID}, this.GetFileOperationCompleted, userState);
        }
        
        private void OnGetFileOperationCompleted(object arg) {
            if ((this.GetFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileCompleted(this, new GetFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/RefreshLookupTable", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RefreshLookupTable() {
            this.Invoke("RefreshLookupTable", new object[0]);
        }
        
        /// <remarks/>
        public void RefreshLookupTableAsync() {
            this.RefreshLookupTableAsync(null);
        }
        
        /// <remarks/>
        public void RefreshLookupTableAsync(object userState) {
            if ((this.RefreshLookupTableOperationCompleted == null)) {
                this.RefreshLookupTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefreshLookupTableOperationCompleted);
            }
            this.InvokeAsync("RefreshLookupTable", new object[0], this.RefreshLookupTableOperationCompleted, userState);
        }
        
        private void OnRefreshLookupTableOperationCompleted(object arg) {
            if ((this.RefreshLookupTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefreshLookupTableCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/UploadFile", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadResponse UploadFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID});
            return ((UploadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID) {
            this.UploadFileAsync(f, MerchantID, MerchantAppUID, AgentID, AgentUID, DocTypeID, OrigName, Source, ConditionID, Description, PrimaryKeyUID, PrimaryKeyID, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/UploadFileWithSource", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadResponse UploadFileWithSource([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID) {
            object[] results = this.Invoke("UploadFileWithSource", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID,
                        MDocSourceID});
            return ((UploadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithSourceAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID) {
            this.UploadFileWithSourceAsync(f, MerchantID, MerchantAppUID, AgentID, AgentUID, DocTypeID, OrigName, Source, ConditionID, Description, PrimaryKeyUID, PrimaryKeyID, MDocSourceID, null);
        }
        
        /// <remarks/>
        public void UploadFileWithSourceAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID, object userState) {
            if ((this.UploadFileWithSourceOperationCompleted == null)) {
                this.UploadFileWithSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithSourceOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithSource", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID,
                        MDocSourceID}, this.UploadFileWithSourceOperationCompleted, userState);
        }
        
        private void OnUploadFileWithSourceOperationCompleted(object arg) {
            if ((this.UploadFileWithSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithSourceCompleted(this, new UploadFileWithSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://MDocWS/UploadFileWithSourceAndUser", RequestNamespace="http://MDocWS/", ResponseNamespace="http://MDocWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadResponse UploadFileWithSourceAndUser([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID, string UserCreated) {
            object[] results = this.Invoke("UploadFileWithSourceAndUser", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID,
                        MDocSourceID,
                        UserCreated});
            return ((UploadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileWithSourceAndUserAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID, string UserCreated) {
            this.UploadFileWithSourceAndUserAsync(f, MerchantID, MerchantAppUID, AgentID, AgentUID, DocTypeID, OrigName, Source, ConditionID, Description, PrimaryKeyUID, PrimaryKeyID, MDocSourceID, UserCreated, null);
        }
        
        /// <remarks/>
        public void UploadFileWithSourceAndUserAsync(byte[] f, int MerchantID, string MerchantAppUID, int AgentID, string AgentUID, int DocTypeID, string OrigName, string Source, int ConditionID, string Description, string PrimaryKeyUID, int PrimaryKeyID, int MDocSourceID, string UserCreated, object userState) {
            if ((this.UploadFileWithSourceAndUserOperationCompleted == null)) {
                this.UploadFileWithSourceAndUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileWithSourceAndUserOperationCompleted);
            }
            this.InvokeAsync("UploadFileWithSourceAndUser", new object[] {
                        f,
                        MerchantID,
                        MerchantAppUID,
                        AgentID,
                        AgentUID,
                        DocTypeID,
                        OrigName,
                        Source,
                        ConditionID,
                        Description,
                        PrimaryKeyUID,
                        PrimaryKeyID,
                        MDocSourceID,
                        UserCreated}, this.UploadFileWithSourceAndUserOperationCompleted, userState);
        }
        
        private void OnUploadFileWithSourceAndUserOperationCompleted(object arg) {
            if ((this.UploadFileWithSourceAndUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileWithSourceAndUserCompleted(this, new UploadFileWithSourceAndUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MDocWS/")]
    public partial class MDoc {
        
        private int docIDField;
        
        private int merchantIDField;
        
        private string merchantAppUIDField;
        
        private int docTypeIDField;
        
        private string docNameField;
        
        private string origNameField;
        
        private int contentSizeField;
        
        private System.DateTime docDateField;
        
        private string sourceField;
        
        private int conditionIDField;
        
        private string descriptionField;
        
        private string primaryKeyUIDField;
        
        private int primaryKeyIDField;
        
        private string mimeTypeField;
        
        private int agentIDField;
        
        private string agentUIDField;
        
        private string fSPathField;
        
        private string docTypeNameField;
        
        private string docTypeDescriptionField;
        
        private string positionField;
        
        private string docTypeGroupNameField;
        
        private string docTypeGroupDescriptionField;
        
        private int docTypeGroupIDField;
        
        private byte[] fileBinaryField;
        
        private bool isDeletedField;
        
        private bool isExistingField;
        
        private int approvalStatusIDField;
        
        private string messageZeusField;
        
        private string messageAgentField;
        
        private System.DateTime approvalEmailSentField;
        
        private int mDocSourceIDField;
        
        private string userCreatedField;
        
        /// <remarks/>
        public int DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        public int MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantAppUID {
            get {
                return this.merchantAppUIDField;
            }
            set {
                this.merchantAppUIDField = value;
            }
        }
        
        /// <remarks/>
        public int DocTypeID {
            get {
                return this.docTypeIDField;
            }
            set {
                this.docTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrigName {
            get {
                return this.origNameField;
            }
            set {
                this.origNameField = value;
            }
        }
        
        /// <remarks/>
        public int ContentSize {
            get {
                return this.contentSizeField;
            }
            set {
                this.contentSizeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int ConditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string PrimaryKeyUID {
            get {
                return this.primaryKeyUIDField;
            }
            set {
                this.primaryKeyUIDField = value;
            }
        }
        
        /// <remarks/>
        public int PrimaryKeyID {
            get {
                return this.primaryKeyIDField;
            }
            set {
                this.primaryKeyIDField = value;
            }
        }
        
        /// <remarks/>
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public int AgentID {
            get {
                return this.agentIDField;
            }
            set {
                this.agentIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgentUID {
            get {
                return this.agentUIDField;
            }
            set {
                this.agentUIDField = value;
            }
        }
        
        /// <remarks/>
        public string FSPath {
            get {
                return this.fSPathField;
            }
            set {
                this.fSPathField = value;
            }
        }
        
        /// <remarks/>
        public string DocTypeName {
            get {
                return this.docTypeNameField;
            }
            set {
                this.docTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string DocTypeDescription {
            get {
                return this.docTypeDescriptionField;
            }
            set {
                this.docTypeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string DocTypeGroupName {
            get {
                return this.docTypeGroupNameField;
            }
            set {
                this.docTypeGroupNameField = value;
            }
        }
        
        /// <remarks/>
        public string DocTypeGroupDescription {
            get {
                return this.docTypeGroupDescriptionField;
            }
            set {
                this.docTypeGroupDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DocTypeGroupID {
            get {
                return this.docTypeGroupIDField;
            }
            set {
                this.docTypeGroupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBinary {
            get {
                return this.fileBinaryField;
            }
            set {
                this.fileBinaryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsExisting {
            get {
                return this.isExistingField;
            }
            set {
                this.isExistingField = value;
            }
        }
        
        /// <remarks/>
        public int ApprovalStatusID {
            get {
                return this.approvalStatusIDField;
            }
            set {
                this.approvalStatusIDField = value;
            }
        }
        
        /// <remarks/>
        public string MessageZeus {
            get {
                return this.messageZeusField;
            }
            set {
                this.messageZeusField = value;
            }
        }
        
        /// <remarks/>
        public string MessageAgent {
            get {
                return this.messageAgentField;
            }
            set {
                this.messageAgentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApprovalEmailSent {
            get {
                return this.approvalEmailSentField;
            }
            set {
                this.approvalEmailSentField = value;
            }
        }
        
        /// <remarks/>
        public int MDocSourceID {
            get {
                return this.mDocSourceIDField;
            }
            set {
                this.mDocSourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserCreated {
            get {
                return this.userCreatedField;
            }
            set {
                this.userCreatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MDocWS/")]
    public partial class UploadResponse {
        
        private int docIDField;
        
        private string statusMessageField;
        
        /// <remarks/>
        public int DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DeleteFileCompletedEventHandler(object sender, DeleteFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetFileCompletedEventHandler(object sender, GetFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MDoc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MDoc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RefreshLookupTableCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UploadFileWithSourceCompletedEventHandler(object sender, UploadFileWithSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UploadFileWithSourceAndUserCompletedEventHandler(object sender, UploadFileWithSourceAndUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileWithSourceAndUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileWithSourceAndUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591